### ISSUE TITLE
Add a lincense file

### ISSUE THREAD

**Issue by mdshaf229** [LFSoftware/modules-laravel#11]
Hi, great project!

Is there a license associated with this project? Could you please add a license file ?  

Thanks!

**Comment by DivineOmega** [comment]
Hi @mdshaf229,

We're licensing this under the Lesser GPL3. See pull request #12.

**Comment by DivineOmega** [comment]
LGPL 3.0 license file has now been added in v1.5.1.

**Comment by mdshaf229** [comment]
Thanks.
